language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

script:
- composer update
- composer dump
- phpunit --version
- bin/phpunit

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs